package com.ld.poetry.entity;

import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableName;

import lombok.Data;
import lombok.EqualsAndHashCode;

import java.math.BigDecimal;
import java.time.Instant;

@Data
@EqualsAndHashCode(callSuper = false)
@TableName("orders")
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;  // ID for the entity, Auto-generated by the database

    @Column(name = "order_id", nullable = false, unique = true)
    private String orderId = generateUniqueId(32);

    @Column(name = "amount", nullable = false)
    private BigDecimal amount = BigDecimal.ONE;

    @Column(name = "ip_address")
    private String ipAddress;

    @Column(name = "payment_type")
    private String paymentType;

    @Column(name = "transaction_id")
    private String transactionId;

    @Column(name = "transaction_info")
    private String transactionInfo;

    @ManyToOne
    @Column(name = "product_id", nullable = true)
    private String productId;

    @ManyToOne
    @Column(name = "system_id", nullable = true)
    private String systemId;

    @Column(name = "create_time")
    private Long createTime = Instant.now().toEpochMilli();

    @Column(name = "update_time")
    private Long updateTime = Instant.now().toEpochMilli();

    // Generate a unique identifier for the order
    private String generateUniqueId(int length) {
        String chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        StringBuilder result = new StringBuilder();
        for (int i = 0; i < length; i++) {
            result.append(chars.charAt((int) (Math.random() * chars.length())));
        }
        return result.toString();
    }

    // Getters and Setters for all fields

}
